# 服务器配置
server:
    port: 8118
    servlet:
        context-path: /ghmall

# 数据库连接配置
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/ghmall?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: gahui
        driver-class-name: com.mysql.jdbc.Driver

# jwt配置
jwt:
    #    token生效时间为30分钟，30*60*1000
    timeout: 1800000
    secret: YHUYbnkdfbjkjhfdhfj

# 访问配置
visit:
#    单纯地从每秒访问次数来限制接口被盗刷或者恶意调用可能不够
#    可以采用，每秒访问如果大于五次，可对ip标记累加一次，若超过20次，则禁止当天访问
    vps: 10

# mybatis配置
mybatis:
    type-aliases-package: com.gahui.ghmall.server.entity
    mapper-locations:
        - classpath*:mapper/*.xml
        - classpath*:dao/*.xml

# 分页配置
pagehelper:
    helper-dialect: mysql
    reasonable: true
    rowBoundsWithCount: true
    offsetAsPageNum: true

# 加密解密配置
aes:
    key: Gtfhhi98&6$##%&*454789F

